# Render Deployment

## Backend Service (render.yaml)
services:
  - type: web
    name: leadgen-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: leadgen-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://leadgen-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

## Steps:
1. Push to GitHub
2. Connect GitHub to Render
3. Create new Web Service
4. Select your repository
5. Configure environment variables
6. Deploy!